<?php
include "../config.php";
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

$user_name = $_SESSION['user']['username'] ?? 'Principal';

// --- DATA FETCHING ---
// 1. KPI Stats
$kpi_query = $conn->query("SELECT 
    COUNT(*) as total,
    SUM(CASE WHEN status='Resolved' THEN 1 ELSE 0 END) as resolved,
    SUM(CASE WHEN status='Open' OR status='In Progress' THEN 1 ELSE 0 END) as pending,
    SUM(CASE WHEN status='Escalated' THEN 1 ELSE 0 END) as escalated
FROM grievances");
$kpi = $kpi_query->fetch_assoc();

// 2. Department Report Data
$summary_q = $conn->query("SELECT 
    branch, 
    COUNT(*) as total,
    SUM(CASE WHEN status='Resolved' THEN 1 ELSE 0 END) as resolved,
    SUM(CASE WHEN status != 'Resolved' THEN 1 ELSE 0 END) as pending
FROM grievances 
WHERE branch IS NOT NULL AND branch != ''
GROUP BY branch
ORDER BY total DESC");

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Grievance Report - <?php echo date("Y-m-d"); ?></title>
    <style>
        body { font-family: 'Times New Roman', Times, serif; color: #000; padding: 40px; }
        
        .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #000; padding-bottom: 20px; }
        .college-name { font-size: 24px; font-weight: bold; text-transform: uppercase; margin-bottom: 5px; }
        .report-title { font-size: 18px; font-weight: bold; margin-bottom: 5px; }
        .report-meta { font-size: 14px; }
        
        h2 { font-size: 16px; border-bottom: 1px solid #000; padding-bottom: 5px; margin-top: 30px; text-transform: uppercase; }
        
        .stats-table, .data-table { width: 100%; border-collapse: collapse; margin-bottom: 20px; font-size: 14px; }
        .stats-table td, .stats-table th, .data-table td, .data-table th { border: 1px solid #000; padding: 8px; text-align: left; }
        .stats-table th, .data-table th { background-color: #f0f0f0; font-weight: bold; }
        
        .footer { margin-top: 60px; display: flex; justify-content: space-between; font-size: 14px; }
        .signature-box { text-align: center; width: 200px; }
        .signature-line { border-top: 1px solid #000; margin-top: 40px; padding-top: 5px; }
        
        @media print {
            button { display: none; }
            body { padding: 0; }
        }
    </style>
</head>
<body onload="window.print()">

    <div style="position: absolute; top: 20px; right: 20px;">
        <button onclick="window.print()" style="padding: 10px 20px; cursor: pointer;">Print Report</button>
    </div>

    <div class="header">
        <div class="college-name">SpeakUp Grievance Management System</div>
        <div class="report-title">Monthly Grievance Report</div>
        <div class="report-meta">Generated on: <?php echo date("F j, Y, g:i a"); ?> | Generated by: <?php echo htmlspecialchars($user_name); ?></div>
    </div>

    <h2>1. Executive Summary</h2>
    <table class="stats-table">
        <tr>
            <th>Total Grievances Received</th>
            <td><?php echo $kpi['total']; ?></td>
        </tr>
        <tr>
            <th>Resolved Cases</th>
            <td><?php echo $kpi['resolved']; ?></td>
        </tr>
        <tr>
            <th>Pending / In Progress</th>
            <td><?php echo $kpi['pending']; ?></td>
        </tr>
        <tr>
            <th>Escalated Issues</th>
            <td><?php echo $kpi['escalated']; ?></td>
        </tr>
    </table>

    <h2>2. Department Performance Analysis</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>Department</th>
                <th style="text-align: center;">Total Issues</th>
                <th style="text-align: center;">Resolved</th>
                <th style="text-align: center;">Pending</th>
                <th style="text-align: center;">Resolution Rate</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            if ($summary_q && $summary_q->num_rows > 0) {
                while($row = $summary_q->fetch_assoc()): 
                    $rate = ($row['total'] > 0) ? round(($row['resolved'] / $row['total']) * 100) . '%' : '0%';
            ?>
            <tr>
                <td><?php echo htmlspecialchars($row['branch']); ?></td>
                <td style="text-align: center;"><?php echo $row['total']; ?></td>
                <td style="text-align: center;"><?php echo $row['resolved']; ?></td>
                <td style="text-align: center;"><?php echo $row['pending']; ?></td>
                <td style="text-align: center;"><?php echo $rate; ?></td>
            </tr>
            <?php endwhile; 
            } else {
                echo "<tr><td colspan='5' style='text-align:center;'>No records found.</td></tr>";
            }
            ?>
        </tbody>
    </table>

    <h2>3. Escalated Issues Pending Review</h2>
    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Issue Title</th>
                <th>Category</th>
                <th>Date Reported</th>
            </tr>
        </thead>
        <tbody>
             <?php
                $esc_q = $conn->query("SELECT id, title, category, incident_date FROM grievances WHERE status = 'Escalated' ORDER BY incident_date DESC");
                if ($esc_q && $esc_q->num_rows > 0) {
                    while($e = $esc_q->fetch_assoc()):
            ?>
            <tr>
                <td>#<?php echo $e['id']; ?></td>
                <td><?php echo htmlspecialchars($e['title']); ?></td>
                <td><?php echo htmlspecialchars($e['category']); ?></td>
                <td><?php echo date("d-m-Y", strtotime($e['incident_date'])); ?></td>
            </tr>
            <?php endwhile; 
                } else {
                    echo "<tr><td colspan='4' style='text-align:center;'>No escalated issues pending.</td></tr>";
                }
            ?>
        </tbody>
    </table>

    <div class="footer">
        <div class="signature-box">
            <div class="signature-line">Principal Signature</div>
        </div>
        <div class="signature-box">
            <div class="signature-line">Committee Head Signature</div>
        </div>
    </div>

</body>
</html>
